refactor: example now compiles but does not work
```
[INFO ] Waiting for JSY-MK-194G startup... (stm32f103 stm32f103/src/main.rs:60)
[ERROR] panicked at /Users/scottgibb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embedded-io-0.7.1/src/lib.rs:412:26:
write() returned Ok(0) (panic_probe panic-probe-1.0.0/src/lib.rs:104)
Firmware exited unexpectedly: Multiple
Core 0
    Frame 0: HardFault_ @ 0x08004712
       /Users/scottgibb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cortex-m-rt-0.7.5/src/lib.rs:1103:1
    Frame 1: HardFault <Cause: Escalated UsageFault <Cause: Undefined instruction>> @ 0x08001390

    Frame 2: __udf @ 0x08001390 inline
       ./asm/lib.rs:48:1
    Frame 3: __udf @ 0x0000000008001390
       ./asm/lib.rs:51:17
    Frame 4: acquire @ 0x0800134a
       /Users/scottgibb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cortex-m-0.7.7/src/critical_section.rs:12:1
```

This seems to be an issue with the HAL itself returning an invalid value

Signed-off-by: Scott Gibb <smgibb@yahoo.com>